### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by krysclick** [hashicorp/terraform-provider-scaffolding-framework#113]
Need help with the terraform CI

**Comment by bflad** [comment]
Hi @krysclick 👋 We will need additional information to provide you assistance, such as what you are trying to accomplish and any unexpected behaviors. In general though, questions about Terraform provider development can be submitted on [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) where there more developers are available to answer questions, rather than this issue tracker which is for bug reports and feature requests for this particular template repository code.
