### ISSUE TITLE
Model declarations in `resource_example.go` are pointer to structs

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform-provider-scaffolding-framework#164]
At e.g. https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/internal/provider/example_resource.go#L93 the model declarations are pointers to structs. I believe these should just be the structs based on my understanding of `.Plan.Get()` and `.State.Get()` functionality, and code elsewhere makes the same declaration (including in the data source example).

**Comment by bflad** [comment]
Hi @mschuchard 👋 Thank you for raising this. While its generally more common to see model variables declared without a pointer, e.g. `var data ExampleResourceModel` (and `&data` in usage), the framework's logic should work fine with the additional pointer. Are you noticing an issue with the extra pointer or just raising this due to the conventional lack of the pointer in the declaration?

**Comment by bflad** [comment]
The internal data handling logic in terraform-plugin-framework (and underlying terraform-plugin-go) has been specifically implemented to be more lenient with accepting double pointers for overwriting target variables since their inception. It makes sense when dealing with `*big.Float` for numbers since its problematic to work with `big.Float` (non-pointer) directly so you'd very much want to do `var whatever *big.Float`, but I'm not exactly sure why that design choice was made for structs and other types as well. Potentially it was just a "well it was done here, let's just do it everywhere" kind of choice because it is not a big deal overall.

In any event, submitted https://github.com/hashicorp/terraform-provider-scaffolding-framework/pull/165 to remove the extraneous pointers in the variable declarations.
