### ISSUE TITLE
Resource "Create" should read from plan, not config?

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform-provider-scaffolding-framework#32]
I could be mistaken on this, but the [documentation](https://www.terraform.io/plugin/framework/resources#create) and [hashicups](https://github.com/hashicorp/terraform-provider-hashicups-pf/blob/3ec094b2a5ff4f0c1c1e6f6de4fd16ef2313b936/hashicups/resource_order.go#L101) all recommend reading from the plan for create.

However, this scaffolding is configured to read from config:
https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/194f73f1efaa94deeca229e10858551d7e2629a8/internal/provider/example_resource.go#L58

edit: As an aside, I'm not super clear on when you _would_ actually read directly from config outside of a data source.

**Comment by Project0** [comment]
Hmm, i stumbled across this as well and i am actually unsure what is the difference. At least documentation is not clear here.
While testing a bit, it seems that Plan may contain unknown values. Config did seem to contain the final values. 

This discussion seems related: https://github.com/hashicorp/terraform-plugin-framework/issues/191#issuecomment-1042480868

Nevertheless, some clarification would be great.

**Comment by bflad** [comment]
Hi @jaygorrell 👋 Thank you for raising this.

Indeed, the general recommendation for the `Create` method is to access the plan instead of configuration. The following documentation and code should reflect this now:

https://www.terraform.io/plugin/framework/resources#create

https://github.com/hashicorp/terraform-provider-hashicups-pf/blob/12e9150e4df62eb6f86dd074936f2c6155865ce5/hashicups/order_resource.go#L143

https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/0c93ae480c4ffb5eb01bf6c66c9af8d8a90744d3/internal/provider/example_resource.go#L86

If there are other locations which reference `req.Config` during `Create` without any comment clarification, please reach out and we'll get those updated.
