### ISSUE TITLE
convertProviderType: incorrect message

### ISSUE THREAD

**Issue by dud225** [hashicorp/terraform-provider-scaffolding-framework#84]
Hello

the `convertProviderType` function is intended to check that the provider in argument ~satisfies the correct interface~ is identical to the type `*scaffoldingProvider`:
```
p, ok := in.(*scaffoldingProvider)
```
and then displays an error if it isn't the case:
```
fmt.Sprintf("While creating the data source or resource, an unexpected provider type (%T) was received. 
This is always a bug in the provider code and should be reported to the provider developers.", p),
```
however if the check fails the value of `p` is the zero value for the type `*scaffoldingProvider`, see: https://go.dev/ref/spec#Type_assertions

As a result `fmt.Sprintf` should print the type of `in`, not `p`

**Comment by bflad** [comment]
Hi @dud225 👋 Thank you for submitting this. There were some changes around the same time to upgrade the provider to framework version 0.13.0 per-resource `Configure` methods, which should now show using the proper input type:

https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/0c93ae480c4ffb5eb01bf6c66c9af8d8a90744d3/internal/provider/example_resource.go#L71-L74

Since this should be covered now, I'm going to close this out, but thank you for the contribution.
